# Generated by Django 3.2.18 on 2023-04-23 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('building', models.CharField(max_length=255, verbose_name='Здание')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('price', models.CharField(max_length=255, verbose_name='Начальная цена')),
                ('count_time_block', models.TimeField(default=datetime.time(0, 40), verbose_name='Затрачиваемое время (лучше кратное 40 мин)')),
            ],
        ),
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчетсво')),
                ('photo', models.ImageField(default='null', null=True, upload_to='images/stylists/')),
                ('about', models.TextField(verbose_name='О себе')),
                ('work_style', models.IntegerField(choices=[(0, 'Без графика'), (1, '5 через 2'), (2, '2 через 2'), (3, '3 через 1')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_clock', models.TimeField(verbose_name='Время')),
            ],
        ),
    ]
