# Generated by Django 3.2.18 on 2023-04-23 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_work', models.DateField(null=True, verbose_name='День')),
                ('is_work', models.BooleanField(default=False, verbose_name='Рабочий день')),
                ('sick_day', models.BooleanField(default=False, verbose_name='Больничный')),
                ('stylist', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='register.stylist', verbose_name='Стилист')),
            ],
        ),
    ]
