# Generated by Django 3.2.18 on 2023-04-23 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('address', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='register.address')),
                ('appointment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.appointment')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.stylist')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.times')),
            ],
        ),
    ]
