# Generated by Django 3.2.18 on 2023-05-24 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_option_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_path', models.ImageField(upload_to='images/portfolio/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('stylist', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='register.stylist', verbose_name='Стилист')),
            ],
        ),
    ]
