# Generated by Django 3.2.18 on 2023-05-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='image_path',
            field=models.ImageField(upload_to='../../media/images/%Y-%m/'),
        ),
    ]
